// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bean/BaseBean.proto

package com.banyue.grpc.bean.base;

public interface BaseBeanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BaseBean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userCode = 1;</code>
   * @return The userCode.
   */
  long getUserCode();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
