// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bean/BaseBean.proto

package com.banyue.grpc.bean.base;

public final class BaseBeanProto {
  private BaseBeanProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseBean_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023bean/BaseBean.proto\"*\n\010BaseBean\022\020\n\010use" +
      "rCode\030\001 \001(\003\022\014\n\004name\030\002 \001(\tB,\n\031com.banyue." +
      "grpc.bean.baseB\rBaseBeanProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BaseBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseBean_descriptor,
        new java.lang.String[] { "UserCode", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
