// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dept/DeptProto.proto

package com.banyue.grpc.dept;

public interface DeptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Dept)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
