// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dept/DeptProto.proto

package com.banyue.grpc.dept;

/**
 * <pre>
 * 方法请求,包含用户名
 * </pre>
 *
 * Protobuf type {@code DeptRequest}
 */
public final class DeptRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DeptRequest)
    DeptRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeptRequest.newBuilder() to construct.
  private DeptRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeptRequest() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeptRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeptRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            com.banyue.grpc.bean.base.BaseBean.Builder subBuilder = null;
            if (bean_ != null) {
              subBuilder = bean_.toBuilder();
            }
            bean_ = input.readMessage(com.banyue.grpc.bean.base.BaseBean.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bean_);
              bean_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banyue.grpc.dept.DeptProto.internal_static_DeptRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banyue.grpc.dept.DeptProto.internal_static_DeptRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banyue.grpc.dept.DeptRequest.class, com.banyue.grpc.dept.DeptRequest.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BEAN_FIELD_NUMBER = 3;
  private com.banyue.grpc.bean.base.BaseBean bean_;
  /**
   * <code>.BaseBean bean = 3;</code>
   * @return Whether the bean field is set.
   */
  @java.lang.Override
  public boolean hasBean() {
    return bean_ != null;
  }
  /**
   * <code>.BaseBean bean = 3;</code>
   * @return The bean.
   */
  @java.lang.Override
  public com.banyue.grpc.bean.base.BaseBean getBean() {
    return bean_ == null ? com.banyue.grpc.bean.base.BaseBean.getDefaultInstance() : bean_;
  }
  /**
   * <code>.BaseBean bean = 3;</code>
   */
  @java.lang.Override
  public com.banyue.grpc.bean.base.BaseBeanOrBuilder getBeanOrBuilder() {
    return getBean();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (bean_ != null) {
      output.writeMessage(3, getBean());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (bean_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBean());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banyue.grpc.dept.DeptRequest)) {
      return super.equals(obj);
    }
    com.banyue.grpc.dept.DeptRequest other = (com.banyue.grpc.dept.DeptRequest) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasBean() != other.hasBean()) return false;
    if (hasBean()) {
      if (!getBean()
          .equals(other.getBean())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasBean()) {
      hash = (37 * hash) + BEAN_FIELD_NUMBER;
      hash = (53 * hash) + getBean().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banyue.grpc.dept.DeptRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.banyue.grpc.dept.DeptRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.banyue.grpc.dept.DeptRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banyue.grpc.dept.DeptRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 方法请求,包含用户名
   * </pre>
   *
   * Protobuf type {@code DeptRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DeptRequest)
      com.banyue.grpc.dept.DeptRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banyue.grpc.dept.DeptProto.internal_static_DeptRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banyue.grpc.dept.DeptProto.internal_static_DeptRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banyue.grpc.dept.DeptRequest.class, com.banyue.grpc.dept.DeptRequest.Builder.class);
    }

    // Construct using com.banyue.grpc.dept.DeptRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      if (beanBuilder_ == null) {
        bean_ = null;
      } else {
        bean_ = null;
        beanBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banyue.grpc.dept.DeptProto.internal_static_DeptRequest_descriptor;
    }

    @java.lang.Override
    public com.banyue.grpc.dept.DeptRequest getDefaultInstanceForType() {
      return com.banyue.grpc.dept.DeptRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.banyue.grpc.dept.DeptRequest build() {
      com.banyue.grpc.dept.DeptRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banyue.grpc.dept.DeptRequest buildPartial() {
      com.banyue.grpc.dept.DeptRequest result = new com.banyue.grpc.dept.DeptRequest(this);
      result.id_ = id_;
      result.name_ = name_;
      if (beanBuilder_ == null) {
        result.bean_ = bean_;
      } else {
        result.bean_ = beanBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banyue.grpc.dept.DeptRequest) {
        return mergeFrom((com.banyue.grpc.dept.DeptRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banyue.grpc.dept.DeptRequest other) {
      if (other == com.banyue.grpc.dept.DeptRequest.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasBean()) {
        mergeBean(other.getBean());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.banyue.grpc.dept.DeptRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.banyue.grpc.dept.DeptRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.banyue.grpc.bean.base.BaseBean bean_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.banyue.grpc.bean.base.BaseBean, com.banyue.grpc.bean.base.BaseBean.Builder, com.banyue.grpc.bean.base.BaseBeanOrBuilder> beanBuilder_;
    /**
     * <code>.BaseBean bean = 3;</code>
     * @return Whether the bean field is set.
     */
    public boolean hasBean() {
      return beanBuilder_ != null || bean_ != null;
    }
    /**
     * <code>.BaseBean bean = 3;</code>
     * @return The bean.
     */
    public com.banyue.grpc.bean.base.BaseBean getBean() {
      if (beanBuilder_ == null) {
        return bean_ == null ? com.banyue.grpc.bean.base.BaseBean.getDefaultInstance() : bean_;
      } else {
        return beanBuilder_.getMessage();
      }
    }
    /**
     * <code>.BaseBean bean = 3;</code>
     */
    public Builder setBean(com.banyue.grpc.bean.base.BaseBean value) {
      if (beanBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bean_ = value;
        onChanged();
      } else {
        beanBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.BaseBean bean = 3;</code>
     */
    public Builder setBean(
        com.banyue.grpc.bean.base.BaseBean.Builder builderForValue) {
      if (beanBuilder_ == null) {
        bean_ = builderForValue.build();
        onChanged();
      } else {
        beanBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.BaseBean bean = 3;</code>
     */
    public Builder mergeBean(com.banyue.grpc.bean.base.BaseBean value) {
      if (beanBuilder_ == null) {
        if (bean_ != null) {
          bean_ =
            com.banyue.grpc.bean.base.BaseBean.newBuilder(bean_).mergeFrom(value).buildPartial();
        } else {
          bean_ = value;
        }
        onChanged();
      } else {
        beanBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.BaseBean bean = 3;</code>
     */
    public Builder clearBean() {
      if (beanBuilder_ == null) {
        bean_ = null;
        onChanged();
      } else {
        bean_ = null;
        beanBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.BaseBean bean = 3;</code>
     */
    public com.banyue.grpc.bean.base.BaseBean.Builder getBeanBuilder() {
      
      onChanged();
      return getBeanFieldBuilder().getBuilder();
    }
    /**
     * <code>.BaseBean bean = 3;</code>
     */
    public com.banyue.grpc.bean.base.BaseBeanOrBuilder getBeanOrBuilder() {
      if (beanBuilder_ != null) {
        return beanBuilder_.getMessageOrBuilder();
      } else {
        return bean_ == null ?
            com.banyue.grpc.bean.base.BaseBean.getDefaultInstance() : bean_;
      }
    }
    /**
     * <code>.BaseBean bean = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.banyue.grpc.bean.base.BaseBean, com.banyue.grpc.bean.base.BaseBean.Builder, com.banyue.grpc.bean.base.BaseBeanOrBuilder> 
        getBeanFieldBuilder() {
      if (beanBuilder_ == null) {
        beanBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.banyue.grpc.bean.base.BaseBean, com.banyue.grpc.bean.base.BaseBean.Builder, com.banyue.grpc.bean.base.BaseBeanOrBuilder>(
                getBean(),
                getParentForChildren(),
                isClean());
        bean_ = null;
      }
      return beanBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DeptRequest)
  }

  // @@protoc_insertion_point(class_scope:DeptRequest)
  private static final com.banyue.grpc.dept.DeptRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banyue.grpc.dept.DeptRequest();
  }

  public static com.banyue.grpc.dept.DeptRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeptRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeptRequest>() {
    @java.lang.Override
    public DeptRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeptRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeptRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeptRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banyue.grpc.dept.DeptRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

