// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dept/DeptProto.proto

package com.banyue.grpc.dept;

public interface DeptRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeptRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.BaseBean bean = 3;</code>
   * @return Whether the bean field is set.
   */
  boolean hasBean();
  /**
   * <code>.BaseBean bean = 3;</code>
   * @return The bean.
   */
  com.banyue.grpc.bean.base.BaseBean getBean();
  /**
   * <code>.BaseBean bean = 3;</code>
   */
  com.banyue.grpc.bean.base.BaseBeanOrBuilder getBeanOrBuilder();
}
