// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dept/DeptProto.proto

package com.banyue.grpc.dept;

public interface DeptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeptResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 code = 1;</code>
   * @return The code.
   */
  long getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  java.util.List<com.banyue.grpc.dept.Dept> 
      getDeptListList();
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  com.banyue.grpc.dept.Dept getDeptList(int index);
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  int getDeptListCount();
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  java.util.List<? extends com.banyue.grpc.dept.DeptOrBuilder> 
      getDeptListOrBuilderList();
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  com.banyue.grpc.dept.DeptOrBuilder getDeptListOrBuilder(
      int index);
}
