// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dept/DeptProto.proto

package com.banyue.grpc.dept;

/**
 * <pre>
 * 方法响应,包含响应的消息
 * </pre>
 *
 * Protobuf type {@code DeptResponse}
 */
public final class DeptResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DeptResponse)
    DeptResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeptResponse.newBuilder() to construct.
  private DeptResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeptResponse() {
    message_ = "";
    deptList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeptResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeptResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            code_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              deptList_ = new java.util.ArrayList<com.banyue.grpc.dept.Dept>();
              mutable_bitField0_ |= 0x00000001;
            }
            deptList_.add(
                input.readMessage(com.banyue.grpc.dept.Dept.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        deptList_ = java.util.Collections.unmodifiableList(deptList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.banyue.grpc.dept.DeptProto.internal_static_DeptResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.banyue.grpc.dept.DeptProto.internal_static_DeptResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.banyue.grpc.dept.DeptResponse.class, com.banyue.grpc.dept.DeptResponse.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private long code_;
  /**
   * <code>int64 code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public long getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPTLIST_FIELD_NUMBER = 3;
  private java.util.List<com.banyue.grpc.dept.Dept> deptList_;
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.banyue.grpc.dept.Dept> getDeptListList() {
    return deptList_;
  }
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.banyue.grpc.dept.DeptOrBuilder> 
      getDeptListOrBuilderList() {
    return deptList_;
  }
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  @java.lang.Override
  public int getDeptListCount() {
    return deptList_.size();
  }
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  @java.lang.Override
  public com.banyue.grpc.dept.Dept getDeptList(int index) {
    return deptList_.get(index);
  }
  /**
   * <code>repeated .Dept deptList = 3;</code>
   */
  @java.lang.Override
  public com.banyue.grpc.dept.DeptOrBuilder getDeptListOrBuilder(
      int index) {
    return deptList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0L) {
      output.writeInt64(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < deptList_.size(); i++) {
      output.writeMessage(3, deptList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < deptList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, deptList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.banyue.grpc.dept.DeptResponse)) {
      return super.equals(obj);
    }
    com.banyue.grpc.dept.DeptResponse other = (com.banyue.grpc.dept.DeptResponse) obj;

    if (getCode()
        != other.getCode()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getDeptListList()
        .equals(other.getDeptListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCode());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getDeptListCount() > 0) {
      hash = (37 * hash) + DEPTLIST_FIELD_NUMBER;
      hash = (53 * hash) + getDeptListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.banyue.grpc.dept.DeptResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.banyue.grpc.dept.DeptResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.banyue.grpc.dept.DeptResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.banyue.grpc.dept.DeptResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 方法响应,包含响应的消息
   * </pre>
   *
   * Protobuf type {@code DeptResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DeptResponse)
      com.banyue.grpc.dept.DeptResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.banyue.grpc.dept.DeptProto.internal_static_DeptResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.banyue.grpc.dept.DeptProto.internal_static_DeptResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.banyue.grpc.dept.DeptResponse.class, com.banyue.grpc.dept.DeptResponse.Builder.class);
    }

    // Construct using com.banyue.grpc.dept.DeptResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDeptListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = 0L;

      message_ = "";

      if (deptListBuilder_ == null) {
        deptList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        deptListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.banyue.grpc.dept.DeptProto.internal_static_DeptResponse_descriptor;
    }

    @java.lang.Override
    public com.banyue.grpc.dept.DeptResponse getDefaultInstanceForType() {
      return com.banyue.grpc.dept.DeptResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.banyue.grpc.dept.DeptResponse build() {
      com.banyue.grpc.dept.DeptResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.banyue.grpc.dept.DeptResponse buildPartial() {
      com.banyue.grpc.dept.DeptResponse result = new com.banyue.grpc.dept.DeptResponse(this);
      int from_bitField0_ = bitField0_;
      result.code_ = code_;
      result.message_ = message_;
      if (deptListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          deptList_ = java.util.Collections.unmodifiableList(deptList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.deptList_ = deptList_;
      } else {
        result.deptList_ = deptListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.banyue.grpc.dept.DeptResponse) {
        return mergeFrom((com.banyue.grpc.dept.DeptResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.banyue.grpc.dept.DeptResponse other) {
      if (other == com.banyue.grpc.dept.DeptResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0L) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (deptListBuilder_ == null) {
        if (!other.deptList_.isEmpty()) {
          if (deptList_.isEmpty()) {
            deptList_ = other.deptList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDeptListIsMutable();
            deptList_.addAll(other.deptList_);
          }
          onChanged();
        }
      } else {
        if (!other.deptList_.isEmpty()) {
          if (deptListBuilder_.isEmpty()) {
            deptListBuilder_.dispose();
            deptListBuilder_ = null;
            deptList_ = other.deptList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            deptListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDeptListFieldBuilder() : null;
          } else {
            deptListBuilder_.addAllMessages(other.deptList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.banyue.grpc.dept.DeptResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.banyue.grpc.dept.DeptResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long code_ ;
    /**
     * <code>int64 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public long getCode() {
      return code_;
    }
    /**
     * <code>int64 code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(long value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.banyue.grpc.dept.Dept> deptList_ =
      java.util.Collections.emptyList();
    private void ensureDeptListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        deptList_ = new java.util.ArrayList<com.banyue.grpc.dept.Dept>(deptList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.banyue.grpc.dept.Dept, com.banyue.grpc.dept.Dept.Builder, com.banyue.grpc.dept.DeptOrBuilder> deptListBuilder_;

    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public java.util.List<com.banyue.grpc.dept.Dept> getDeptListList() {
      if (deptListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deptList_);
      } else {
        return deptListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public int getDeptListCount() {
      if (deptListBuilder_ == null) {
        return deptList_.size();
      } else {
        return deptListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public com.banyue.grpc.dept.Dept getDeptList(int index) {
      if (deptListBuilder_ == null) {
        return deptList_.get(index);
      } else {
        return deptListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder setDeptList(
        int index, com.banyue.grpc.dept.Dept value) {
      if (deptListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeptListIsMutable();
        deptList_.set(index, value);
        onChanged();
      } else {
        deptListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder setDeptList(
        int index, com.banyue.grpc.dept.Dept.Builder builderForValue) {
      if (deptListBuilder_ == null) {
        ensureDeptListIsMutable();
        deptList_.set(index, builderForValue.build());
        onChanged();
      } else {
        deptListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder addDeptList(com.banyue.grpc.dept.Dept value) {
      if (deptListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeptListIsMutable();
        deptList_.add(value);
        onChanged();
      } else {
        deptListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder addDeptList(
        int index, com.banyue.grpc.dept.Dept value) {
      if (deptListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeptListIsMutable();
        deptList_.add(index, value);
        onChanged();
      } else {
        deptListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder addDeptList(
        com.banyue.grpc.dept.Dept.Builder builderForValue) {
      if (deptListBuilder_ == null) {
        ensureDeptListIsMutable();
        deptList_.add(builderForValue.build());
        onChanged();
      } else {
        deptListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder addDeptList(
        int index, com.banyue.grpc.dept.Dept.Builder builderForValue) {
      if (deptListBuilder_ == null) {
        ensureDeptListIsMutable();
        deptList_.add(index, builderForValue.build());
        onChanged();
      } else {
        deptListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder addAllDeptList(
        java.lang.Iterable<? extends com.banyue.grpc.dept.Dept> values) {
      if (deptListBuilder_ == null) {
        ensureDeptListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deptList_);
        onChanged();
      } else {
        deptListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder clearDeptList() {
      if (deptListBuilder_ == null) {
        deptList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        deptListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public Builder removeDeptList(int index) {
      if (deptListBuilder_ == null) {
        ensureDeptListIsMutable();
        deptList_.remove(index);
        onChanged();
      } else {
        deptListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public com.banyue.grpc.dept.Dept.Builder getDeptListBuilder(
        int index) {
      return getDeptListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public com.banyue.grpc.dept.DeptOrBuilder getDeptListOrBuilder(
        int index) {
      if (deptListBuilder_ == null) {
        return deptList_.get(index);  } else {
        return deptListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public java.util.List<? extends com.banyue.grpc.dept.DeptOrBuilder> 
         getDeptListOrBuilderList() {
      if (deptListBuilder_ != null) {
        return deptListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deptList_);
      }
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public com.banyue.grpc.dept.Dept.Builder addDeptListBuilder() {
      return getDeptListFieldBuilder().addBuilder(
          com.banyue.grpc.dept.Dept.getDefaultInstance());
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public com.banyue.grpc.dept.Dept.Builder addDeptListBuilder(
        int index) {
      return getDeptListFieldBuilder().addBuilder(
          index, com.banyue.grpc.dept.Dept.getDefaultInstance());
    }
    /**
     * <code>repeated .Dept deptList = 3;</code>
     */
    public java.util.List<com.banyue.grpc.dept.Dept.Builder> 
         getDeptListBuilderList() {
      return getDeptListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.banyue.grpc.dept.Dept, com.banyue.grpc.dept.Dept.Builder, com.banyue.grpc.dept.DeptOrBuilder> 
        getDeptListFieldBuilder() {
      if (deptListBuilder_ == null) {
        deptListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.banyue.grpc.dept.Dept, com.banyue.grpc.dept.Dept.Builder, com.banyue.grpc.dept.DeptOrBuilder>(
                deptList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        deptList_ = null;
      }
      return deptListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DeptResponse)
  }

  // @@protoc_insertion_point(class_scope:DeptResponse)
  private static final com.banyue.grpc.dept.DeptResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.banyue.grpc.dept.DeptResponse();
  }

  public static com.banyue.grpc.dept.DeptResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeptResponse>
      PARSER = new com.google.protobuf.AbstractParser<DeptResponse>() {
    @java.lang.Override
    public DeptResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeptResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeptResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeptResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.banyue.grpc.dept.DeptResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

