// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vo/BaseVo.proto

package com.banyue.grpc.vo.base;

public final class BaseVoProto {
  private BaseVoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseVo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017vo/BaseVo.proto\032\031google/protobuf/any.p" +
      "roto\",\n\006BaseVo\022\"\n\004data\030\003 \003(\0132\024.google.pr" +
      "otobuf.AnyB(\n\027com.banyue.grpc.vo.baseB\013B" +
      "aseVoProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_BaseVo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseVo_descriptor,
        new java.lang.String[] { "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
