// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vo/BaseVo.proto

package com.banyue.grpc.vo.base;

public interface BaseVoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BaseVo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.protobuf.Any data = 3;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getDataList();
  /**
   * <code>repeated .google.protobuf.Any data = 3;</code>
   */
  com.google.protobuf.Any getData(int index);
  /**
   * <code>repeated .google.protobuf.Any data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .google.protobuf.Any data = 3;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any data = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder(
      int index);
}
