server:
  port: 0
spring:
  application:
    name: micro-service-grpc-server  #微服务名称，对外暴漏的微服务名称，十分重要

eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      #defaultZone: http://127.0.0.1:7001/eureka  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/  #将服务注册到集群

  instance:
    instance-id: micro-service-grpc-server #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址
grpc:
  server:
    port: 0

